openapi: 3.0.0
info:
  version: 1.0.0
  title: Login API

paths:
  /login:
    post:
      description: Login to the application
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Successful login
        401:
          description: Unauthorized
